additionalProperties:
  npmName: '@fauxify/api-client'
  supportsES6: true
  packageVersion: '1.0.0'
  npmVersion: '1.0.0'
  useSingleRequestParameter: true
  stringEnums: true
  modelPropertyNaming: 'original'
  prependFormOrBodyParameters: true
  modelPackage: 'models'
  apiPackage: 'api'
  withSeparateModelsAndApi: true
  withoutFactory: true
