/* tslint:disable */
/* eslint-disable */
/**
 * Fauxify API
 * API for managing artists, albums, songs, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Song } from './song';

/**
 * 
 * @export
 * @interface SongsGet200Response
 */
export interface SongsGet200Response {
    /**
     * 
     * @type {Array<Song>}
     * @memberof SongsGet200Response
     */
    'results'?: Array<Song>;
    /**
     * 
     * @type {number}
     * @memberof SongsGet200Response
     */
    'count'?: number;
}

