/* tslint:disable */
/* eslint-disable */
/**
 * Fauxify API
 * API for managing artists, albums, songs, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SongAnalyticsInput
 */
export interface SongAnalyticsInput {
    /**
     * 
     * @type {string}
     * @memberof SongAnalyticsInput
     */
    'songId': string;
    /**
     * 
     * @type {number}
     * @memberof SongAnalyticsInput
     */
    'playTime': number;
    /**
     * 
     * @type {string}
     * @memberof SongAnalyticsInput
     */
    'userId': string;
}

